### ISSUE TITLE
Controller enable gpio output.

### ISSUE THREAD

**Issue by maxlock** [pico-cs/firmware#2]
Hi, it would be very useful to control a gpio pin and not just the LED output when the controller is enabled. This will make it very simple for the pico-cs to be used with many H-bridge modules with an enable input as the booster. Without this some DCC locos when attached to DC power (no dcc signal) assume they're in DC mode and start to accelerate.
Again, this is great work! Thanks, Max.

**Comment by stfnmllr** [comment]
You might test https://github.com/pico-cs/firmware/releases/tag/v0.3.0.  With this version GP22 reflects the 'enabled status'.

**Comment by maxlock** [comment]
That's working nicely, thanks!
