### ISSUE TITLE
Inverted signal output.

### ISSUE THREAD

**Issue by maxlock** [pico-cs/firmware#3]
Hi, another feature idea! If you add a second inverted signal output that would enable a user to use a common H-bridge module as a booster without having to [build a signal inverter](https://dcc-ex.com/_images/inverter1.jpg).

**Comment by stfnmllr** [comment]
You might test https://github.com/pico-cs/firmware/releases/tag/v0.3.0.  With this version an inverted DCC signal is available at GP3.

**Comment by maxlock** [comment]
Thanks, something isn't quite right, with my inverter in place feeding an hbridge I get the correct signal at the rails. Disconnecting the hbridge from the inverted signal and connecting to the pico inverted output, I only see the signal on one rail. I'll put my scope on the pico later and give you a better description.

**Comment by stfnmllr** [comment]
Hm, I guess your wiring needs to use both outputs - the normal and the inverted one - maybe https://dcc-ex.com/reference/hardware/motorboards/L298N-motor-board-setup.html would be of help or is it that the inverted signal never 'delivers' a high state?

**Comment by maxlock** [comment]
Yes, that's very similar to the hbridge module I'm testing with. I think a good test would be a two LEDs connected in opposing orientation across the inverted and non-inverted pico outputs. If both LEDs light then it's working. If only one, then it's not. I'll test later today.

**Comment by maxlock** [comment]
I did a quick test, both LEDs light, so there is an interverted output from the pico. I'll test it all later with the scope.

**Comment by maxlock** [comment]
I did a quick test, with two LEDs across the pico signal outputs, and I only get one lit, so either the inverted output isn't in phase with the non-inverted output or the non-inverted output isn't working. I'll probe it with my scope later this evening.

**Comment by maxlock** [comment]
OK, I put the scope on the pico. GP3 is just 3.3v DC with no DCC signal.

**Comment by stfnmllr** [comment]
Ah, ok - not good :-) Then I do need to double check why the GP is inverted only but the signal is missing...

**Comment by stfnmllr** [comment]
If you want you might give it another try with https://github.com/pico-cs/firmware/tree/v0.3.2-rc1 - cannot test currently, so I would only be able to confirm later...

**Comment by stfnmllr** [comment]
...validated signal output on inverted GP3 with https://github.com/pico-cs/firmware/releases/tag/v0.3.2

**Comment by maxlock** [comment]
Excellent! I've just tested with a couple of LEDs and both are lit. I'll give it a proper test with a loco later. Thanks for addiing this!

**Comment by maxlock** [comment]
I've just tested with a loco, and it works great. Additionally the adc and gpio functions are exactly what I was thinking could be done as well. Thanks! :D
