### ISSUE TITLE
Feature, generate a push message if an input gpio changes state.

### ISSUE THREAD

**Issue by maxlock** [pico-cs/firmware#4]
Again, great work so far! The last feature which would make pico-cs able to completely run a small layout is to have a push message (as per the protocol document) generated when a GPIO configured as an input changes state. This would allow control software to react to things like a block occupancy or position sensor without having to continually poll and potentially miss events.

**Comment by stfnmllr** [comment]
Yes, sure - had this already on the todo list :-)

**Comment by stfnmllr** [comment]
Is now available with https://github.com/pico-cs/firmware/releases/tag/v0.5.2

**Comment by maxlock** [comment]
Thankyou! that's working perfectly here! Do you have a roadmap for this project at all or any discussion group etc? It's a really nice project!

**Comment by stfnmllr** [comment]
Did enable 'discussions' on pico-cs org level: https://github.com/orgs/pico-cs/discussions
