### ISSUE TITLE
Does not reconnect to wifi if disconnected.

### ISSUE THREAD

**Issue by maxlock** [pico-cs/firmware#5]
Hi, glad to see the latest 0.8.0 release and improvements. I've noticed that if using the firmware without the mqtt gateway that due to a lack of traffic many wireless APs will disconnect the client. I had a look at the source and in loop_pico_w it doesn't appear to check if it's been disconnected, and reconnect. I tried adding the following to the loop

        if (cyw43_wifi_link_status(&cyw43_state, CYW43_ITF_STA) != CYW43_LINK_UP) {
            cyw43_arch_wifi_connect_timeout_ms(WIFI_SSID, WIFI_PASSWORD, CYW43_AUTH_WPA2_AES_PSK, 30000);
        }

But I'm no C coder and it doesn't appear to work either :D

Thanks for your efforts so far, this is a great solution for small layouts.

**Comment by stfnmllr** [comment]
Hello, thanks for  reporting the issue!

Please check if the re-connect would work with 0.8.1 release candidate branch https://github.com/pico-cs/firmware/tree/v0.8.1.
At least in case of a connection issue, the error would be logged to the USB output.

Please let me know about the outcome - thanks!

**Comment by maxlock** [comment]
Hi, Yes that looks better I can see it reconnecting now. In my case I think my AP (openwrt) is being a bit aggressive and ultimately deauthenticating the pico off after a number of reconnects though that's not an issue with pico-cs. :)

Mon Nov  6 11:46:13 2023 daemon.info hostapd: lan: STA 28:cd:c1:08:e9:0f IEEE 802.11: associated (aid 1)
Mon Nov  6 11:46:13 2023 daemon.notice hostapd: lan: AP-STA-CONNECTED 28:cd:c1:08:e9:0f
Mon Nov  6 11:46:13 2023 daemon.info hostapd: lan: STA 28:cd:c1:08:e9:0f WPA: pairwise key handshake completed (RSN)
Mon Nov  6 11:46:13 2023 daemon.info dnsmasq-dhcp[4062]: DHCPREQUEST(br-lan) 172.31.255.249 28:cd:c1:08:e9:0f
Mon Nov  6 11:46:13 2023 daemon.info dnsmasq-dhcp[4062]: DHCPACK(br-lan) 172.31.255.249 28:cd:c1:08:e9:0f PicoW
Mon Nov  6 11:46:15 2023 daemon.info dnsmasq-dhcp[4062]: DHCPDISCOVER(br-lan) 28:cd:c1:08:e9:0f
Mon Nov  6 11:46:15 2023 daemon.info dnsmasq-dhcp[4062]: DHCPOFFER(br-lan) 172.31.255.249 28:cd:c1:08:e9:0f
Mon Nov  6 11:46:15 2023 daemon.info dnsmasq-dhcp[4062]: DHCPREQUEST(br-lan) 172.31.255.249 28:cd:c1:08:e9:0f
Mon Nov  6 11:46:15 2023 daemon.info dnsmasq-dhcp[4062]: DHCPACK(br-lan) 172.31.255.249 28:cd:c1:08:e9:0f PicoW
Mon Nov  6 11:46:20 2023 daemon.info hostapd: lan: STA 28:cd:c1:08:e9:0f IEEE 802.11: authenticated
Mon Nov  6 11:51:34 2023 daemon.notice hostapd: lan: AP-STA-DISCONNECTED 28:cd:c1:08:e9:0f
Mon Nov  6 11:51:34 2023 daemon.info hostapd: lan: STA 28:cd:c1:08:e9:0f IEEE 802.11: disassociated due to inactivity
Mon Nov  6 11:51:35 2023 daemon.info hostapd: lan: STA 28:cd:c1:08:e9:0f IEEE 802.11: associated (aid 1)
Mon Nov  6 11:51:35 2023 daemon.notice hostapd: lan: AP-STA-CONNECTED 28:cd:c1:08:e9:0f
Mon Nov  6 11:51:35 2023 daemon.info hostapd: lan: STA 28:cd:c1:08:e9:0f WPA: pairwise key handshake completed (RSN)
Mon Nov  6 11:51:44 2023 daemon.info hostapd: lan: STA 28:cd:c1:08:e9:0f IEEE 802.11: authenticated
Mon Nov  6 11:56:57 2023 daemon.notice hostapd: lan: AP-STA-DISCONNECTED 28:cd:c1:08:e9:0f
Mon Nov  6 11:56:57 2023 daemon.info hostapd: lan: STA 28:cd:c1:08:e9:0f IEEE 802.11: disassociated due to inactivity
Mon Nov  6 11:56:57 2023 daemon.info hostapd: lan: STA 28:cd:c1:08:e9:0f IEEE 802.11: associated (aid 1)
Mon Nov  6 11:56:57 2023 daemon.notice hostapd: lan: AP-STA-CONNECTED 28:cd:c1:08:e9:0f
Mon Nov  6 11:56:57 2023 daemon.info hostapd: lan: STA 28:cd:c1:08:e9:0f WPA: pairwise key handshake completed (RSN)
Mon Nov  6 11:57:06 2023 daemon.info hostapd: lan: STA 28:cd:c1:08:e9:0f IEEE 802.11: authenticated
Mon Nov  6 12:02:08 2023 daemon.notice hostapd: lan: AP-STA-DISCONNECTED 28:cd:c1:08:e9:0f
Mon Nov  6 12:02:08 2023 daemon.info hostapd: lan: STA 28:cd:c1:08:e9:0f IEEE 802.11: disassociated due to inactivity
Mon Nov  6 12:02:09 2023 daemon.info hostapd: lan: STA 28:cd:c1:08:e9:0f IEEE 802.11: associated (aid 1)
Mon Nov  6 12:02:09 2023 daemon.notice hostapd: lan: AP-STA-CONNECTED 28:cd:c1:08:e9:0f
Mon Nov  6 12:02:09 2023 daemon.info hostapd: lan: STA 28:cd:c1:08:e9:0f WPA: pairwise key handshake completed (RSN)
Mon Nov  6 12:02:09 2023 daemon.info hostapd: lan: STA 28:cd:c1:08:e9:0f IEEE 802.11: authenticated
Mon Nov  6 12:07:18 2023 daemon.notice hostapd: lan: AP-STA-DISCONNECTED 28:cd:c1:08:e9:0f
Mon Nov  6 12:07:18 2023 daemon.info hostapd: lan: STA 28:cd:c1:08:e9:0f IEEE 802.11: disassociated due to inactivity
Mon Nov  6 12:07:19 2023 daemon.info hostapd: lan: STA 28:cd:c1:08:e9:0f IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)

**Comment by stfnmllr** [comment]
Yes, did see that there are lots of complaints about this openwrt issue on the internet. The pico-cs firmware does answer 'pings' in case this would help to keep the connection alive.

**Comment by stfnmllr** [comment]
new version https://github.com/pico-cs/firmware/releases/tag/v0.8.1 is available now
